-- HOLODRUM
-- Horon Village
-- locations
HoronVillage = OoSLocation.New("HoronVillage")
HoronShop = OoSLocation.New("HoronShop")
AdvanceShop = OoSLocation.New("AdvanceShop")
MemberShop = OoSLocation.New("MemberShop")
MayorHouse = OoSLocation.New("MayorHouse")
MayorBombWall = OoSLocation.New("MayorBombWall")
ClockShop = OoSLocation.New("ClockShop")
MakuTree = OoSLocation.New("MakuTree")
Vasu = OoSLocation.New("Vasu")
DrLeft = OoSLocation.New("DrLeft")
DrLeftBackyard = OoSLocation.New("DrLeftBackyard")
HoronOldMan = OoSLocation.New("HoronOldMan")
HoronPortalStairs = OoSLocation.New("HoronPortalStairs")
HoronPortal = OoSLocation.New("HoronPortal")
HoronVillageOldMan = OoSLocation.New("HoronVillageOldMan")

-- items
HoronMushroomChest = OoSLocation.New("HoronMushroomChest")
HoronTreeHP = OoSLocation.New("HoronTreeHP")
HoronTree = OoSLocation.New("HoronTree")
HoronShop1 = OoSLocation.New("HoronShop1")
HoronShop2 = OoSLocation.New("HoronShop2")
HoronShop3 = OoSLocation.New("HoronShop3")
MembersShop1 = OoSLocation.New("MembersShop1")
MembersShop2 = OoSLocation.New("MembersShop2")
MembersShop3 = OoSLocation.New("MembersShop3")
AdvanceShop1 = OoSLocation.New("AdvanceShop1")
AdvanceShop2 = OoSLocation.New("AdvanceShop2")
AdvanceShop3 = OoSLocation.New("AdvanceShop3")
VasuGift = OoSLocation.New("VasuGift")
MayorsGift = OoSLocation.New("MayorsGift")
HoronGasha = OoSLocation.New("HoronGasha")
ClockShopTrade = OoSLocation.New("ClockShopTrade")
DrLeftReward = OoSLocation.New("DrLeftReward")
DrLeftBackyardChest = OoSLocation.New("DrLeftBackyardChest")
MakuTreeGift = OoSLocation.New("MakuTreeGift")
MakuTreeReward1 = OoSLocation.New("MakuTreeReward1")
MakuTreeReward2 = OoSLocation.New("MakuTreeReward2")
MakuTreeReward3 = OoSLocation.New("MakuTreeReward3")
HoronVillageOldManGift = OoSLocation.New("HoronVillageOldManGift")
MakuSeed = OoSLocation.New("MakuSeed")

-- North Horon
-- locations
LowerNorthHoron = OoSLocation.New("LowerNorthHoron")
UpperNorthHoron = OoSLocation.New("UpperNorthHoron")
EasternNorthHoron = OoSLocation.New("EasternNorthHoron")
EyeglassLake = OoSLocation.New("EyeglassLake")
DryEyeglassLake = OoSLocation.New("DryEyeglassLake")
FrozenEyeglassLake = OoSLocation.New("FrozenEyeglassLake")
MalonHouse = OoSLocation.New("MalonHouse")
NorthHoronOldMan = OoSLocation.New("NorthHoronOldMan")
GnarledRootDoorstep = OoSLocation.New("GnarledRootDoorstep")
GnarledRootDungeon = OoSLocation.New("GnarledRootDungeon")
RedRingOldMan = OoSLocation.New("RedRingOldMan")
DryEyeglassBombCave = OoSLocation.New("DryEyeglassBombCave")
DryEyeglassHiddenStairs = OoSLocation.New("DryEyeglassHiddenStairs")
EyeglassPortal = OoSLocation.New("EyeglassPortal")
UnicornCave = OoSLocation.New("UnicornCave")
-- items
MalonTrade = OoSLocation.New("MalonTrade")
CatInTree = OoSLocation.New("CatInTree")
EyeglassPitsChest = OoSLocation.New("EyeglassPitsChest")
NorthHoronGasha = OoSLocation.New("NorthHoronGasha")
NorthHoronOldManGift = OoSLocation.New("NorthHoronOldManGift")
RedRingOldManReward = OoSLocation.New("RedRingOldManReward")
DryEyeglassBombCaveChest = OoSLocation.New("DryEyeglassBombCaveChest")
DryEyeglassHiddenStairsChest = OoSLocation.New("DryEyeglassHiddenStairsChest")
EyeglassGasha = OoSLocation.New("EyeglassGasha")

-- Western Coast
-- locations
EastWesternCoast = OoSLocation.New("EastWesternCoast")
WestWesternCoast = OoSLocation.New("WestWesternCoast")
WesternCoastOldMan = OoSLocation.New("WesternCoastOldMan")
WesternCoastHouse = OoSLocation.New("WesternCoastHouse")
WesternCoastStump = OoSLocation.New("WesternCoastStump")
Graveyard = OoSLocation.New("Graveyard")
GraveyardWinter = OoSLocation.New("GraveyardWinter")
GraveyardAutumn = OoSLocation.New("GraveyardAutumn")
-- items
BlackBeast = OoSLocation.New("BlackBeast")
WesternCoastChest = OoSLocation.New("WesternCoastChest")
WesternCoastHouseChest = OoSLocation.New("WesternCoastHouseChest")
WesternCoastGasha = OoSLocation.New("WesternCoastGasha")
GraveyardHP = OoSLocation.New("GraveyardHP")
HerosCave = OoSLocation.New("HerosCave")
ExplorersCrypt = OoSLocation.New("ExplorersCrypt")
GoldenDarknutKill = OoSLocation.New("GoldenDarknutKill")

-- Eastern Suburbs
-- locations
LowerEasternSuburbs = OoSLocation.New("LowerEasternSuburbs")
WindmillLedge = OoSLocation.New("WindmillLedge")
SuburbsSpringCave = OoSLocation.New("SuburbsSpringCave")
SuburbsPortal = OoSLocation.New("SuburbsPortal")
UpperEasternSuburbs = OoSLocation.New("UpperEasternSuburbs")
UpperEasternSuburbsWinter = OoSLocation.New("UpperEasternSuburbsWinter")
SuburbsOldMan = OoSLocation.New("SuburbsOldMan")
SamasaDesert = OoSLocation.New("SamasaDesert")
-- items
WindmillHP = OoSLocation.New("WindmillHP")
WindmillTrade = OoSLocation.New("WindmillTrade")
SuburbsSpringCave = OoSLocation.New("SuburbsSpringCave")
SuburbsGasha = OoSLocation.New("SuburbsGasha")
SuburbsHP = OoSLocation.New("SuburbsHP")
SamasaDesertPit = OoSLocation.New("SamasaDesertPit")
SamasaDesertChest = OoSLocation.New("SamasaDesertChest")
SamasaDesertGasha = OoSLocation.New("SamasaDesertGasha")
GoldenMoblinKill = OoSLocation.New("GoldenMoblinKill")

-- Woods of Winter
-- locations
MoblinRoad = OoSLocation.New("MoblinRoad")
MoblinRoadBombCave = OoSLocation.New("MoblinRoadBombCave")
Holly = OoSLocation.New("Holly")
WoodsOfWinter = OoSLocation.New("WoodsOfWinter")
WoodsOfWinterMushroomCave = OoSLocation.New("WoodsOfWinterMushroomCave")
SnakesRemains = OoSLocation.New("SnakesRemains")
UpperSnakesRemains = OoSLocation.New("UpperSnakesRemains")
-- items
MoblinRoadBombCaveChest = OoSLocation.New("MoblinRoadBombCaveChest")
MoblinRoadWaterfallCaveChest = OoSLocation.New("MoblinRoadWaterfallCaveChest")
WoodsOfWinterTree = OoSLocation.New("WoodsOfWinterTree")
WoodsOfWinterMushroomCaveChest = OoSLocation.New("WoodsOfWinterMushroomCaveChest")

-- Holodrum Plain
NorthHolodrumPlain = OoSLocation.New("NorthHolodrumPlain")
NorthHolodrumPlainOldMan = OoSLocation.New("NorthHolodrumPlainOldMan")
SouthHolodrumPlain = OoSLocation.New("SouthHolodrumPlain")
HolodrumPlainSign = OoSLocation.New("HolodrumPlainSign")
-- items
HolodrumPlainTree = OoSLocation.New("HolodrumPlainTree")
Blaino = OoSLocation.New("Blaino")
HolodrumPlainMushroomCave = OoSLocation.New("HolodrumPlainMushroomCave")
UnderNatzuBridge = OoSLocation.New("UnderNatzuBridge")
HolodrumPlainFloodedCave = OoSLocation.New("HolodrumPlainFloodedCave")
MrsRuul = OoSLocation.New("MrsRuul")
SouthHolodrumPlainGasha = OoSLocation.New("SouthHolodrumPlainGasha")
HolodrumPlainIsland = OoSLocation.New("HolodrumPlainIsland")
SouthHolodrumPlainOldMan = OoSLocation.New("SouthHolodrumPlainOldMan")
TreehouseOldMan = OoSLocation.New("TreehouseOldMan")
OnoxGasha = OoSLocation.New("OnoxGasha")

-- Spool Swamp
-- locations
NorthSpoolSwamp = OoSLocation.New("NorthSpoolSwamp")
FloodgateKeeper = OoSLocation.New("FloodgateKeeper")
FloodgateKeyhole = OoSLocation.New("FloodgateKeyhole")
SpoolSwampStump = OoSLocation.New("SpoolSwampStump")
PoisonMothLair = OoSLocation.New("PoisonMothLair")
MiddleSpoolSwamp = OoSLocation.New("MiddleSpoolSwamp")
SouthSpoolSwamp = OoSLocation.New("SouthSpoolSwamp")
SpringSpoolSwamp = OoSLocation.New("SpringSpoolSwamp")
SummerSpoolSwamp = OoSLocation.New("SummerSpoolSwamp")
AutumnSpoolSwamp = OoSLocation.New("AutumnSpoolSwamp")
WinterSpoolSwamp = OoSLocation.New("WinterSpoolSwamp")
SwampSouthGashaArea = OoSLocation.New("SwampGashaSpot")
SpoolWinterCave = OoSLocation.New("SpoolWinterCave")
SpoolPortal = OoSLocation.New("SpoolPortal")
-- items
SwampTree = OoSLocation.New("SwampTree")
SwampVasuDigSpot = OoSLocation.New("SwampVasuDigSpot")
FloodgateLever = OoSLocation.New("FloodgateLever")
SwampNorthGashaSpot = OoSLocation.New("SwampNorthGashaSpot")
SwampFloodedHP = OoSLocation.New("SwampFloodedHP")
SwampBombCave = OoSLocation.New("SwampBombCave")
SwampSouthGashaSpot = OoSLocation.New("SwampSouthGashaSpot")
GoldenOctorokKill = OoSLocation.New("GoldenOctorokKill")

-- Natzu
-- locations
NatzuWest = OoSLocation.New("NatzuWest")
NatzuRickyWest = OoSLocation.New("NatzuRickyWest")
NatzuRickyEast = OoSLocation.New("NatzuRickyEast")
NatzuDimitriWest = OoSLocation.New("NatzuDimitriWest")
NatzuDimitriEast = OoSLocation.New("NatzuDimitriEast")
NatzuMooshWest = OoSLocation.New("NatzuMooshWest")
NatzuMooshEast = OoSLocation.New("NatzuMooshEast")
MoblinKeepBridge = OoSLocation.New("MoblinKeepBridge")
MoblinKeep = OoSLocation.New("MoblinKeep")
SunkenDoorstep = OoSLocation.New("SunkenDoorstep")
-- items
NatzuPlatformCave = OoSLocation.New("NatzuPlatformCave")
GreatMoblinChest = OoSLocation.New("GreatMoblinChest")

-- Sunken City
SunkenCity = OoSLocation.New("SunkenCity")
SunkenDimitri = OoSLocation.New("SunkenDimitri")
Syrup = OoSLocation.New("Syrup")
NorthSunkenCity = OoSLocation.New("NorthSunkenCity")
-- items
SunkenTree = OoSLocation.New("SunkenTree")
SunkenSummerCave = OoSLocation.New("SunkenSummerCave")
SunkenVaseTrade = OoSLocation.New("SunkenVaseTrade")
MasterChallenge = OoSLocation.New("MasterChallenge")
MasterDiver = OoSLocation.New("MasterDiver")
SunkenMasterDiverChest = OoSLocation.New("SunkenMasterDiverChest")
SunkenGashaSpot = OoSLocation.New("SunkenGashaSpot")

-- Mount Cucco
LowerMtCucco = OoSLocation.New("LowerMtCucco")
CuccoRightMountain = OoSLocation.New("CuccoRightMountain")
UpperMtCucco = OoSLocation.New("UpperMtCucco")
DragonKeyhole = OoSLocation.New("DragonKeyhole")
DancingDragonDungeon = OoSLocation.New("DancingDragonDungeon")
-- items
TalonReward = OoSLocation.New("TalonReward")
TalonChest = OoSLocation.New("TalonChest")
MtCuccoScrubLeft = OoSLocation.New("MtCuccoScrubLeft")
MtCuccoScrubRight = OoSLocation.New("MtCuccoScrubRight")
BananaTree = OoSLocation.New("BananaTree")
MtCuccoPlatformCave = OoSLocation.New("MtCuccoPlatformCave")
MtCuccoLedge = OoSLocation.New("MtCuccoLedge")
MtCuccoDiveSpot = OoSLocation.New("MtCuccoDiveSpot")
MtCuccoGasha = OoSLocation.New("MtCuccoGasha")

-- Goron Mountain
CenterGoronMountain = OoSLocation.New("CenterGoronMountain")
WestGoronMountain = OoSLocation.New("WestGoronMountain")
SouthGoronMountain = OoSLocation.New("SouthGoronMountain")
-- items
GoronGashaWest = OoSLocation.New("GoronGashaWest")
GoronGashaEast = OoSLocation.New("GoronGashaEast")
GoronMountainOldMan = OoSLocation.New("GoronMountainOldMan")
LonelyGoron = OoSLocation.New("LonelyGoron")
GoronPitsItem = OoSLocation.New("GoronPitsItem")
GoronLavaChest = OoSLocation.New("GoronLavaChest")
Biggoron = OoSLocation.New("Biggoron")

-- Tarm Ruins
TarmEntrance = OoSLocation.New("TarmEntrance")
TarmTreeStump = OoSLocation.New("TarmTreeStump")
TarmSecretDeku = OoSLocation.New("TarmSecretDeku")
LostWoods = OoSLocation.New("LostWoods")
TarmTree = OoSLocation.New("TarmTree")
UpperTarm = OoSLocation.New("UpperTarm")
D6Doorstep = OoSLocation.New("D6Doorstep")
AncientRuins = OoSLocation.New("AncientRuins")
-- items
GoldenLynelKill = OoSLocation.New("GoldenLynelKill")
Pedestal = OoSLocation.New("Pedestal")
TarmGasha = OoSLocation.New("TarmGasha")
TarmMushroomTreeChest = OoSLocation.New("TarmMushroomTreeChest")
TarmOldMan = OoSLocation.New("TarmOldMan")

-- Temple Remains
LowerTempleRemains = OoSLocation.New("LowerTempleRemains")
TempleRemainsStump = OoSLocation.New("TempleRemainsStump")
TempleRemainsLowerPortal = OoSLocation.New("TempleRemainsLowerPortal")
TempleRemainsBombCave = OoSLocation.New("TempleRemainsBombCave")
TempleRemainsUpperPortal = OoSLocation.New("TempleRemainsUpperPortal")

-- SUBROSIA
-- Mountain
SubrosiaMountainEast = OoSLocation.New("SubrosiaMountainEast")
SubrosiaMountainMagnetDigSpot = OoSLocation.New("SubrosiaMountainMagnetDigSpot")
SubrosiaMountainTempleDigSpot = OoSLocation.New("SubrosiaMountainTempleDigSpot")
SmithyHardOre = OoSLocation.New("SmithyHardOre")
SmithyBell = OoSLocation.New("SmithyBell")
SubrosiaChef = OoSLocation.New("SubrosiaChef")
SubrosiaMountainWest = OoSLocation.New("SubrosiaMountainWest")
SubrosiaMountainLockedChest = OoSLocation.New("SubrosiaMountainLockedChest")
SubrosiaMountainWestDigSpot = OoSLocation.New("SubrosiaMountainWestDigSpot")
SubrosiaMountainSouthDigSpot = OoSLocation.New("SubrosiaMountainSouthDigSpot")
Volcano = OoSLocation.New("Volcano")
Fireworks = OoSLocation.New("Fireworks")

-- Temple
TempleOfSeasons = OoSLocation.New("TempleOfSeasons")
TempleDigSpot = OoSLocation.New("TempleDigSpot")
TempleWinterFairy = OoSLocation.New("TempleWinterFairy")
TempleSummerFairy = OoSLocation.New("TempleSummerFairy")
TempleAutumnEntrance = OoSLocation.New("TempleAutumnEntrance")
TempleAutumnFairy = OoSLocation.New("TempleAutumnFairy")

-- Market
SubrosiaMarket = OoSLocation.New("SubrosiaMarket")
RosaDate = OoSLocation.New("RosaDate")
SubrosiaMarket1 = OoSLocation.New("SubrosiaMarket1")
SubrosiaMarket2 = OoSLocation.New("SubrosiaMarket2")
SubrosiaMarket3 = OoSLocation.New("SubrosiaMarket3")
SubrosiaMarket4 = OoSLocation.New("SubrosiaMarket4")
SubrosiaMarket5 = OoSLocation.New("SubrosiaMarket5")
BeachDigSpot = OoSLocation.New("BeachDigSpot")
SubrosiaMarketUpperDigSpot = OoSLocation.New("SubrosiaMarketUpperDigSpot")
SubrosiaMarketLowerDigSpot = OoSLocation.New("SubrosiaMarketLowerDigSpot")

-- Village
StrangeBrothers = OoSLocation.New("StrangeBrothers")
VillagerGasha = OoSLocation.New("VillagerGasha")
StrangeBrothersTreasure = OoSLocation.New("StrangeBrothersTreasure")
TempleSpringFairy = OoSLocation.New("TempleSpringFairy")
SubrosiaWilds = OoSLocation.New("SubrosiaWilds")
SubrosiaWildsMagnet = OoSLocation.New("SubrosiaWildsMagnet")
WildsDigSpot = OoSLocation.New("WildsDigSpot")
SubrosiaVillagePortal = OoSLocation.New("SubrosiaVillagePortal")

-- Pirates
Pirates = OoSLocation.New("Pirates")

-- Furnace
EastFurnace = OoSLocation.New("EastFurnace")
WestFurnace = OoSLocation.New("WestFurnace")
SouthFurnace = OoSLocation.New("SouthFurnace")
GreatFurnace = OoSLocation.New("GreatFurnace")
SignGuy = OoSLocation.New("SignGuy")
BombFlowerPickup = OoSLocation.New("BombFlowerPickup")
FurnaceTerrace = OoSLocation.New("FurnaceTerrace")

-- D8
SwordAndShieldMaze = OoSLocation.New("SwordAndShieldMaze")

-- DUNGEONS
-- Hero's Cave
HerosCaveFoyer = OoSLocation.New("HerosCaveFoyer")
HerosCaveLedge = OoSLocation.New("HerosCaveLedge")
HerosCaveUnderground = OoSLocation.New("HerosCaveUnderground")
HerosCavePostKey = OoSLocation.New("HerosCavePostKey")

-- Gnarled Root Dungeon
GnarledFoyer = OoSLocation.New("GnarledFoyer")
GnarledFloormasters = OoSLocation.New("GnarledFloormasters")
GnarledLeftStalfos = OoSLocation.New("GnarledLeftStalfos")
GnarledZolRoom = OoSLocation.New("GnarledZolRoom")
GnarledGoriyaRoom = OoSLocation.New("GnarledGoriyaRoom")
GnarledPushBlocks = OoSLocation.New("GnarledPushBlocks")
GnarledMinecartChest = OoSLocation.New("GnarledMinecartChest")
GoriyaBros = OoSLocation.New("GoriyaBros")
Aquamentus = OoSLocation.New("Aquamentus")
GnarledEssence = OoSLocation.New("GnarledEssence")
-- items
GnarledRightStalfosChest = OoSLocation.New("GnarledRightStalfosChest")
GnarledFloormasterChest = OoSLocation.New("GnarledFloormasterChest")
GnarledLeftStalfosChest = OoSLocation.New("GnarledLeftStalfosChest")
GnarledGoriyaChest = OoSLocation.New("GnarledGoriyaChest")
GnarledLeverChest = OoSLocation.New("GnarledLeverChest")
GnarledSpinningBladeChest = OoSLocation.New("GnarledSpinningBladeChest")
GnarledPostGoriyaBros = OoSLocation.New("GnarledPostGoriyaBros")

-- Snake's Remains
-- locations
SnakeFoyer = OoSLocation.New("SnakeFoyer")
SnakeAngryTorches = OoSLocation.New("SnakeAngryTorches")
SnakeMoblinRopeFight = OoSLocation.New("SnakeMoblinRopeFight")
SnakeRupeeRoom = OoSLocation.New("SnakeRupeeRoom")
SnakeHardhats = OoSLocation.New("SnakeHardhats")
SnakeBombMoblins = OoSLocation.New("SnakeBombMoblins")
SnakeBladeTraps = OoSLocation.New("SnakeBladeTraps")
SnakeAltEntrance = OoSLocation.New("SnakeAltEntrance")
SnakeBombPuzzle = OoSLocation.New("SnakeBombPuzzle")
SnakeBombBlockStairs = OoSLocation.New("SnakeBombBlockStairs")
FacadeDoorstep = OoSLocation.New("FacadeDoorstep")
Facade = OoSLocation.New("Facade")
KingDodongo = OoSLocation.New("KingDodongo")
SnakeEssence = OoSLocation.New("SnakeEssence")
-- items
SnakeLeftRopeDrop = OoSLocation.New("SnakeLeftRopeDrop")
SnakeRightRopeChest = OoSLocation.New("SnakeRightRopeChest")
SnakeHardhatChest = OoSLocation.New("SnakeHardhatChest")
SnakeTerrace = OoSLocation.New("SnakeTerrace")

-- Poison Moth's Lair
PoisonFoyer = OoSLocation.New("PoisonFoyer")
PoisonCentral = OoSLocation.New("PoisonCentral")
PoisonWaterRoom = OoSLocation.New("PoisonWaterRoom")
PoisonPols = OoSLocation.New("PoisonPols")
PoisonTrampolineOwl = OoSLocation.New("PoisonTrampolineOwl")
PoisonTrampolinePuzzle = OoSLocation.New("PoisonTrampolinePuzzle")
PoisonOmuaiDoorstep = OoSLocation.New("PoisonOmuaiDoorstep")
Omuai = OoSLocation.New("Omuai")
Mothula = OoSLocation.New("Mothula")
-- items
PoisonWaterChest = OoSLocation.New("PoisonWaterChest")
PoisonTrampolineOwlChest = OoSLocation.New("PoisonTrampolineOwlChest")
PoisonZolChest = OoSLocation.New("PoisonZolChest")
PoisonRollerChest = OoSLocation.New("PoisonRollerChest")
PoisonMoldormChest = OoSLocation.New("PoisonMoldormChest")
PoisonBombWallChest = OoSLocation.New("PoisonBombWallChest")
PoisonMimicChest = OoSLocation.New("PoisonMimicChest")
PoisonTerraceChest = OoSLocation.New("PoisonTerraceChest")
PoisonBladeTrapChest = OoSLocation.New("PoisonBladeTrapChest")
PoisonEssence = OoSLocation.New("PoisonEssence")

-- Dancing Dragon Dungeon
DancingFoyer = OoSLocation.New("DancingFoyer")
DancingMinecart = OoSLocation.New("DancingMinecart")
DancingAntiFairyMaze = OoSLocation.New("DancingAntiFairyMaze")
DancingSpikeTrap = OoSLocation.New("DancingSpikeTrap")
DancingPostWaterRollers = OoSLocation.New("DancingPostWaterRollers")
DancingMinecartTorches = OoSLocation.New("DancingMinecartTorches")
Agunima = OoSLocation.New("Agunima")
DancingBranchingMinecart = OoSLocation.New("DancingBranchingMinecart")
DancingWizzrobes = OoSLocation.New("DancingWizzrobes")
DancingBeamos = OoSLocation.New("DancingBeamos")
DancingTorchPit = OoSLocation.New("DancingTorchPit")
DancingPotHeaven = OoSLocation.New("DancingPotHeaven")
Gohma = OoSLocation.New("Gohma")
-- items
DancingPotPush = OoSLocation.New("DancingPotPush")
DancingDarkRoomChest = OoSLocation.New("DancingDarkRoomChest")
DancingWaterRing = OoSLocation.New("DancingWaterRing")
DancingPoolDrop = OoSLocation.New("DancingPoolDrop")
DancingTorchChest = OoSLocation.New("DancingTorchChest")
DancingRegrowingEmbers = OoSLocation.New("DancingRegrowingEmbers")
DancingPitRace = OoSLocation.New("DancingPitRace")
DancingEyeDive = OoSLocation.New("DancingEyeDive")
DancingEssence = OoSLocation.New("DancingEssence")

-- Unicorn's Cave
UnicornFoyer = OoSLocation.New("UnicornFoyer")
UnicornMinecarts = OoSLocation.New("UnicornMinecarts")
UnicornMinecartPushBlock = OoSLocation.New("UnicornMinecartPushBlock")
UnicornUndergroundPipesRight = OoSLocation.New("UnicornUndergroundPipesRight")
UnicornPotRoom = OoSLocation.New("UnicornPotRoom")
UnicornMagnetGloveChest = OoSLocation.New("UnicornMagnetGloveChest")
UnicornFireStatues = OoSLocation.New("UnicornFireStatues")
UnicornPreSyger = OoSLocation.New("UnicornPreSyger")
Syger = OoSLocation.New("Syger")
UnicornPostSyger = OoSLocation.New("UnicornPostSyger")
UnicornMagnetButton = OoSLocation.New("UnicornMagnetButton")
Digdogger = OoSLocation.New("Digdogger")
UnicornEssence = OoSLocation.New("UnicornEssence")
-- items
UnicornChestLeftOfEntrance = OoSLocation.New("UnicornChestLeftOfEntrance")
UnicornTerrace = OoSLocation.New("UnicornTerrace")
UnicornSpiralChest = OoSLocation.New("UnicornSpiralChest")
UnicornMiddleMinecartChest = OoSLocation.New("UnicornMiddleMinecartChest")
UnicornRightMinecartChest = OoSLocation.New("UnicornRightMinecartChest")
UnicornArmosPuzzle = OoSLocation.New("UnicornArmosPuzzle")
UnicornSpinnerChest = OoSLocation.New("UnicornSpinnerChest")
UnicornGibdoZolChest = OoSLocation.New("UnicornGibdoZolChest")
UnicornTreadmillBasement = OoSLocation.New("UnicornTreadmillBasement")

-- Ancient Ruins
AncientFoyer = OoSLocation.New("AncientFoyer")
AncientRightOfSpinner = OoSLocation.New("AncientRightOfSpinner")
AncientRupeeRoom = OoSLocation.New("AncientRupeeRoom")
AncientRopeSpinnerWest = OoSLocation.New("AncientRopeSpinnerWest")
AncientBeamosPlatforms = OoSLocation.New("AncientBeamosPlatforms")
Ancient2FGibdo = OoSLocation.New("Ancient2FGibdo")
AncientSpinyTrampoline = OoSLocation.New("AncientSpinyTrampoline")
AncientArrowTrap = OoSLocation.New("AncientArrowTrap")
AncientArmosDarknutDrop = OoSLocation.New("AncientArmosDarknutDrop")
AncientIndyJones = OoSLocation.New("AncientIndyJones")
AncientVireDoorstep = OoSLocation.New("AncientVireDoorstep")
Vire = OoSLocation.New("Vire")
AncientGauntlet = OoSLocation.New("AncientGauntlet")
AncientBossDoor = OoSLocation.New("AncientBossDoor")
Manhandla = OoSLocation.New("Manhandla")
-- items
AncientMagnetBallDrop = OoSLocation.New("AncientMagnetBallDrop")
AncientTrappedChest = OoSLocation.New("AncientTrappedChest")
AncientNorthOfSpinnerChest = OoSLocation.New("AncientNorthOfSpinnerChest")
AncientMagicBoomerangChest = OoSLocation.New("AncientMagicBoomerangChest")
AncientBossKeyChest = OoSLocation.New("AncientBossKeyChest")
AncientEssence = OoSLocation.New("AncientEssence")

-- Explorer's Crypt
-- locations
CryptFoyer = OoSLocation.New("CryptFoyer")
Crypt1FLeftOfPoe = OoSLocation.New("Crypt1FLeftOfPoe")
Crypt1FLeftOfPoeChest = OoSLocation.New("Crypt1FLeftOfPoeChest")
CryptFirstPoe = OoSLocation.New("CryptFirstPoe")
Crypt1FKeyRoom = OoSLocation.New("Crypt1FKeyRoom")
CryptSurroundedByArmos = OoSLocation.New("CryptSurroundedByArmos")
CryptPoeTrampoline = OoSLocation.New("CryptQuicksandRoom")
CryptArmosPuzzle = OoSLocation.New("CryptArmosPuzzle")
CryptMagunesu = OoSLocation.New("CryptMagunesu")
CryptPoe2Trampoline = OoSLocation.New("CryptPoe2Trampoline")
CryptPoe2 = OoSLocation.New("CryptPoe2")
CryptDarknutBridge = OoSLocation.New("CryptDarknutBridge")
CryptDarknutBridgeTrampolines = OoSLocation.New("CryptDarknutBridgeTrampolines")
CryptPastDarknutBridge = OoSLocation.New("CryptPastDarknutBridge")
CryptFastPlatform = OoSLocation.New("CryptFastPlatform")
CryptPrePoeSisters = OoSLocation.New("CryptPrePoeSisters")
PoeSisters = OoSLocation.New("PoeSisters")
CryptStairMaze = OoSLocation.New("CryptStairMaze")
CryptWizzrobeStalfosRoom = OoSLocation.New("CryptWizzrobeStalfosRoom")
CryptJumpingStalfos = OoSLocation.New("CryptJumpingStalfos")
Gleeok = OoSLocation.New("Gleeok")
-- items
Crypt1FWizzrobeChest = OoSLocation.New("Crypt1FWizzrobeChest")
CryptZolTrampoline = OoSLocation.New("CryptZolTrampoline")
Crypt1FKeyRoomChest = OoSLocation.New("Crypt1FKeyRoomChest")
CryptArmosPuzzleReward = OoSLocation.New("CryptArmosPuzzleReward")
CryptMagunesuReward = OoSLocation.New("CryptMagunesuReward")
CryptQuicksandChest = OoSLocation.New("CryptQuicksandChest")
CryptFastPlatformChest = OoSLocation.New("CryptFastPlatformChest")
CryptStairMazeChest = OoSLocation.New("CryptStairMazeChest")
CryptWizzrobeStalfosChest = OoSLocation.New("CryptWizzrobeStalfosChest")
CryptJumpingStalfosChest = OoSLocation.New("CryptJumpingStalfosChest")
CryptEssence = OoSLocation.New("CryptEssence")

-- Sword & Shield Maze
MazeFoyer = OoSLocation.New("MazeFoyer")
MazeHardhats = OoSLocation.New("MazeHardhats")
MazeBigBladeTrap = OoSLocation.New("MazeBigBladeTrap")
MazeSpinner = OoSLocation.New("MazeSpinner")
MazeThreeEyeOwl = OoSLocation.New("MazeThreeEyeOwl")
Frypolar = OoSLocation.New("Frypolar")
MazeNineTorches = OoSLocation.New("MazeNineTorches")
MazeIcePuzzle = OoSLocation.New("MazeIcePuzzle")
MazeTerrace = OoSLocation.New("MazeTerrace")
MazeNevermeltIce = OoSLocation.New("MazeNevermeltIce")
MazeNEIceDrop = OoSLocation.New("MazeNEIceDrop")
MazeNWIceDrop = OoSLocation.New("MazeNWIceDrop")
MazeMedusaDoorstep = OoSLocation.New("MazeMedusaDoorstep")
MedusaHead = OoSLocation.New("MedusaHead")
MazeEssence = OoSLocation.New("MazeEssence")
-- items
MazeEyeDrop = OoSLocation.New("MazeEyeDrop")
MazeThreeEyeChest = OoSLocation.New("MazeThreeEyeChest")
MazeHardhatDrop = OoSLocation.New("MazeHardhatDrop")
MazeArmosChest = OoSLocation.New("MazeArmosChest")
MazeThreeEyeBombChest = OoSLocation.New("MazeThreeEyeBombChest")
MazeGhostArmos = OoSLocation.New("MazeGhostArmos")
MazeSELavaChest = OoSLocation.New("MazeSELavaChest")
MazeSparkPots = OoSLocation.New("MazeSparkPots")

-- Goal
OnoxCastle = OoSLocation.New("OnoxCastle")
Ganon = OoSLocation.New("Ganon")