StartLocation = Region.New("StartLocation")
-- HOLODRUM
Maple = Region.New("Maple")
MapleTrade = Region.New("MapleTrade")
Maple1 = Region.New("Maple1")
Maple2 = Region.New("Maple2")
Maple3 = Region.New("Maple3")
Maple4 = Region.New("Maple4")
-- Horon Village
-- locations
HoronVillage = Region.New("HoronVillage")
HoronShop = Region.New("HoronShop")
AdvanceShop = Region.New("AdvanceShop")
MemberShop = Region.New("MemberShop")
MayorHouse = Region.New("MayorHouse")
MayorBombWall = Region.New("MayorBombWall")
ClockShop = Region.New("ClockShop")
MakuTree = Region.New("MakuTree")
Vasu = Region.New("Vasu")
DrLeft = Region.New("DrLeft")
DrLeftBackyard = Region.New("DrLeftBackyard")
HoronPortalStairs = Region.New("HoronPortalStairs")
HoronPortal = Region.New("HoronPortal")
-- items
HoronVillageFindSeason = Region.New("HoronVillageFindSeason")
HoronMushroomChest = Region.New("HoronMushroomChest")
HoronTreeHP = Region.New("HoronTreeHP")
HoronTree = Region.New("HoronTree")
VasuGift = Region.New("VasuGift")
MayorsGift = Region.New("MayorsGift")
MayorSecret = Region.New("MayorSecret")
HoronGasha = Region.New("HoronGasha")
ClockShopTrade = Region.New("ClockShopTrade")
ClockShopSecret = Region.New("ClockShopSecret")
DrLeftReward = Region.New("DrLeftReward")
DrLeftBackyardChest = Region.New("DrLeftBackyardChest")
MakuTreeGift = Region.New("MakuTreeGift")
MakuTreeReward1 = Region.New("MakuTreeReward1")
MakuTreeReward2 = Region.New("MakuTreeReward2")
MakuTreeReward3 = Region.New("MakuTreeReward3")
HoronVillageOldMan = Region.New("HoronVillageOldMan")

-- North Horon
-- locations
LowerNorthHoron = Region.New("LowerNorthHoron")
UpperNorthHoron = Region.New("UpperNorthHoron")
EasternNorthHoron = Region.New("EasternNorthHoron")
EyeglassLake = Region.New("EyeglassLake")
DryEyeglassLake = Region.New("DryEyeglassLake")
FrozenEyeglassLake = Region.New("FrozenEyeglassLake")
MalonHouse = Region.New("MalonHouse")
GnarledRootDoorstep = Region.New("GnarledRootDoorstep")
GnarledRootDungeon = Region.New("GnarledRootDungeon")
RedRingOldMan = Region.New("RedRingOldMan")
DryEyeglassBombCave = Region.New("DryEyeglassBombCave")
DryEyeglassHiddenStairs = Region.New("DryEyeglassHiddenStairs")
EyeglassPortal = Region.New("EyeglassPortal")
UnicornCave = Region.New("UnicornCave")
-- items
NorthHoronFindSeason = Region.New("NorthHoronFindSeason")
MalonTrade = Region.New("MalonTrade")
CatInTree = Region.New("CatInTree")
EyeglassPitsChest = Region.New("EyeglassPitsChest")
NorthHoronGasha = Region.New("NorthHoronGasha")
NorthHoronOldMan = Region.New("NorthHoronOldMan")
RedRingOldManReward = Region.New("RedRingOldManReward")
DryEyeglassBombCaveChest = Region.New("DryEyeglassBombCaveChest")
DryEyeglassHiddenStairsChest = Region.New("DryEyeglassHiddenStairsChest")
EyeglassGasha = Region.New("EyeglassGasha")

-- Western Coast
-- locations
EastWesternCoast = Region.New("EastWesternCoast")
WestWesternCoast = Region.New("WestWesternCoast")
WesternCoastOldMan = Region.New("WesternCoastOldMan")
WesternCoastHouse = Region.New("WesternCoastHouse")
WesternCoastStump = Region.New("WesternCoastStump")
Graveyard = Region.New("Graveyard")
GraveyardWinter = Region.New("GraveyardWinter")
GraveyardAutumn = Region.New("GraveyardAutumn")
-- items
WesternCoastFindSeason = Region.New("WesternCoastFindSeason")
BlackBeast = Region.New("BlackBeast")
WesternCoastChest = Region.New("WesternCoastChest")
WesternCoastHouseChest = Region.New("WesternCoastHouseChest")
WesternCoastGasha = Region.New("WesternCoastGasha")
GraveyardHP = Region.New("GraveyardHP")
GraveyardSecret = Region.New("GraveyardSecret")
HerosCave = Region.New("HerosCave")
ExplorersCrypt = Region.New("ExplorersCrypt")
GoldenDarknutKill = Region.New("GoldenDarknutKill")

-- Eastern Suburbs
-- locations
LowerEasternSuburbs = Region.New("LowerEasternSuburbs")
WindmillLedge = Region.New("WindmillLedge")
SuburbsPortal = Region.New("SuburbsPortal")
UpperEasternSuburbs = Region.New("UpperEasternSuburbs")
UpperEasternSuburbsWinter = Region.New("UpperEasternSuburbsWinter")
SuburbsOldMan = Region.New("SuburbsOldMan")
SamasaDesert = Region.New("SamasaDesert")
-- items
EasternSuburbsFindSeason = Region.New("EasternSuburbsFindSeason")
WindmillHP = Region.New("WindmillHP")
WindmillTrade = Region.New("WindmillTrade")
SuburbsSpringCave = Region.New("SuburbsSpringCave")
SuburbsGasha = Region.New("SuburbsGasha")
SuburbsHP = Region.New("SuburbsHP")
SamasaDesertPit = Region.New("SamasaDesertPit")
SamasaDesertChest = Region.New("SamasaDesertChest")
SamasaDesertGasha = Region.New("SamasaDesertGasha")
SamasaScrub = Region.New("SamasaScrub")
GoldenMoblinKill = Region.New("GoldenMoblinKill")

-- Woods of Winter
-- locations
MoblinRoad = Region.New("MoblinRoad")
MoblinRoadBombCave = Region.New("MoblinRoadBombCave")
Holly = Region.New("Holly")
WoodsOfWinter = Region.New("WoodsOfWinter")
WoodsOfWinterMushroomCave = Region.New("WoodsOfWinterMushroomCave")
SnakesRemains = Region.New("SnakesRemains")
UpperSnakesRemains = Region.New("UpperSnakesRemains")
-- items
WoodsOfWinterFindSeason = Region.New("WoodsOfWinterFindSeason")
MoblinRoadBombCaveChest = Region.New("MoblinRoadBombCaveChest")
MoblinRoadWaterfallCaveChest = Region.New("MoblinRoadWaterfallCaveChest")
WoodsOfWinterTree = Region.New("WoodsOfWinterTree")
WoodsOfWinterMushroomCaveChest = Region.New("WoodsOfWinterMushroomCaveChest")

-- Holodrum Plain
NorthHolodrumPlain = Region.New("NorthHolodrumPlain")
NorthHolodrumPlainOldMan = Region.New("NorthHolodrumPlainOldMan")
SouthHolodrumPlain = Region.New("SouthHolodrumPlain")
HolodrumPlainSign = Region.New("HolodrumPlainSign")
-- items
HolodrumPlainFindSeason = Region.New("HolodrumPlainFindSeason")
HolodrumPlainTree = Region.New("HolodrumPlainTree")
Blaino = Region.New("Blaino")
HolodrumPlainMushroomCave = Region.New("HolodrumPlainMushroomCave")
UnderNatzuBridge = Region.New("UnderNatzuBridge")
HolodrumPlainFloodedCave = Region.New("HolodrumPlainFloodedCave")
MrsRuul = Region.New("MrsRuul")
SouthHolodrumPlainGasha = Region.New("SouthHolodrumPlainGasha")
HolodrumPlainIsland = Region.New("HolodrumPlainIsland")
SouthHolodrumPlainOldMan = Region.New("SouthHolodrumPlainOldMan")
TreehouseOldMan = Region.New("TreehouseOldMan")
OnoxGasha = Region.New("OnoxGasha")

-- Spool Swamp
-- locations
NorthSpoolSwamp = Region.New("NorthSpoolSwamp")
FloodgateKeeper = Region.New("FloodgateKeeper")
FloodgateKeyhole = Region.New("FloodgateKeyhole")
SpoolSwampStump = Region.New("SpoolSwampStump")
PoisonMothLair = Region.New("PoisonMothLair")
MiddleSpoolSwamp = Region.New("MiddleSpoolSwamp")
SouthSpoolSwamp = Region.New("SouthSpoolSwamp")
SpringSpoolSwamp = Region.New("SpringSpoolSwamp")
SummerSpoolSwamp = Region.New("SummerSpoolSwamp")
AutumnSpoolSwamp = Region.New("AutumnSpoolSwamp")
WinterSpoolSwamp = Region.New("WinterSpoolSwamp")
SwampSouthGashaArea = Region.New("SwampGashaSpot")
SpoolWinterCave = Region.New("SpoolWinterCave")
SpoolPortal = Region.New("SpoolPortal")
-- items
SpoolSwampFindSeason = Region.New("SpoolSwampFindSeason")
SwampTree = Region.New("SwampTree")
SwampVasuDigSpot = Region.New("SwampVasuDigSpot")
FloodgateLever = Region.New("FloodgateLever")
SwampNorthGashaSpot = Region.New("SwampNorthGashaSpot")
SwampScrub = Region.New("SwampScrub")
SwampFloodedHP = Region.New("SwampFloodedHP")
SwampBombCave = Region.New("SwampBombCave")
SwampSouthGashaSpot = Region.New("SwampSouthGashaSpot")
GoldenOctorokKill = Region.New("GoldenOctorokKill")

-- Natzu
-- locations
NatzuWest = Region.New("NatzuWest")
NatzuRickyWest = Region.New("NatzuRickyWest")
NatzuRickyEast = Region.New("NatzuRickyEast")
NatzuDimitriWest = Region.New("NatzuDimitriWest")
NatzuDimitriEast = Region.New("NatzuDimitriEast")
NatzuMooshWest = Region.New("NatzuMooshWest")
NatzuMooshEast = Region.New("NatzuMooshEast")
NatzuScrub = Region.New("NatzuScrub")
MoblinKeepBridge = Region.New("MoblinKeepBridge")
MoblinKeep = Region.New("MoblinKeep")
SunkenDoorstep = Region.New("SunkenDoorstep")
-- items
NatzuPlatformCave = Region.New("NatzuPlatformCave")
GreatMoblinChest = Region.New("GreatMoblinChest")
DekuSecret = Region.New("DekuSecret")

-- Sunken City
SunkenCity = Region.New("SunkenCity")
SunkenDimitri = Region.New("SunkenDimitri")
Syrup = Region.New("Syrup")
NorthSunkenCity = Region.New("NorthSunkenCity")
-- items
SunkenCityFindSeason = Region.New("SunkenCityFindSeason")
SunkenTree = Region.New("SunkenTree")
SunkenSummerCave = Region.New("SunkenSummerCave")
SunkenVaseTrade = Region.New("SunkenVaseTrade")
MasterChallenge = Region.New("MasterChallenge")
MasterDiver = Region.New("MasterDiver")
DiverSecret = Region.New("DiverSecret")
SunkenMasterDiverChest = Region.New("SunkenMasterDiverChest")
SunkenGashaSpot = Region.New("SunkenGashaSpot")
SyrupShop = Region.New("SyrupShop")

-- Mount Cucco
LowerMtCucco = Region.New("LowerMtCucco")
CuccoRightMountain = Region.New("CuccoRightMountain")
UpperMtCucco = Region.New("UpperMtCucco")
TalonCave = Region.New("TalonCave")
DragonKeyhole = Region.New("DragonKeyhole")
DancingDragonDungeon = Region.New("DancingDragonDungeon")
RoosterAdventure = Region.New("RoosterAdventure")
-- items
TalonReward = Region.New("TalonReward")
TalonChest = Region.New("TalonChest")
MtCuccoScrubLeft = Region.New("MtCuccoScrubLeft")
MtCuccoScrubRight = Region.New("MtCuccoScrubRight")
BananaTree = Region.New("BananaTree")
MtCuccoPlatformCave = Region.New("MtCuccoPlatformCave")
MtCuccoLedge = Region.New("MtCuccoLedge")
MtCuccoDiveSpot = Region.New("MtCuccoDiveSpot")
MtCuccoGasha = Region.New("MtCuccoGasha")

-- Goron Mountain
CenterGoronMountain = Region.New("CenterGoronMountain")
WestGoronMountain = Region.New("WestGoronMountain")
SouthGoronMountain = Region.New("SouthGoronMountain")
-- items
GoronGashaWest = Region.New("GoronGashaWest")
GoronGashaEast = Region.New("GoronGashaEast")
GoronMountainOldMan = Region.New("GoronMountainOldMan")
LonelyGoron = Region.New("LonelyGoron")
GoronPitsItem = Region.New("GoronPitsItem")
GoronLavaChest = Region.New("GoronLavaChest")
Biggoron = Region.New("Biggoron")
BiggoronSecret = Region.New("BiggoronSecret")

-- Tarm Ruins
TarmEntrance = Region.New("TarmEntrance")
TarmTreeStump = Region.New("TarmTreeStump")
TarmLostWoodsScrub = Region.New("TarmLostWoodsScrub")
TarmPedestalScrub = Region.New("TarmPedestalScrub")
LostWoods = Region.New("LostWoods")
TarmTree = Region.New("TarmTree")
TarmSeedTree = Region.New("TarmSeedTree")
UpperTarm = Region.New("UpperTarm")
D6Doorstep = Region.New("D6Doorstep")
AncientRuins = Region.New("AncientRuins")
-- items
LostWoodsFindSeason = Region.New("LostWoodsFindSeason")
TarmRuinsFindSeason = Region.New("TarmRuinsFindSeason")
GoldenLynelKill = Region.New("GoldenLynelKill")
Pedestal = Region.New("Pedestal")
TarmGasha = Region.New("TarmGasha")
TarmMushroomTreeChest = Region.New("TarmMushroomTreeChest")
TarmOldMan = Region.New("TarmOldMan")

-- Temple Remains
TempleRemainsFindSeason = Region.New("TempleRemainsFindSeason")
LowerTempleRemains = Region.New("LowerTempleRemains")
TempleRemainsStump = Region.New("TempleRemainsStump")
TempleRemainsLowerPortal = Region.New("TempleRemainsLowerPortal")
TempleRemainsBombCave = Region.New("TempleRemainsBombCave")
TempleRemainsUpperPortal = Region.New("TempleRemainsUpperPortal")

-- SUBROSIA
-- Mountain
SubrosiaMountainEast = Region.New("SubrosiaMountainEast")
SubrosiaMountainMagnetDigSpot = Region.New("SubrosiaMountainMagnetDigSpot")
SubrosiaMountainTempleDigSpot = Region.New("SubrosiaMountainTempleDigSpot")
SubrosianSecret = Region.New("SubrosianSecret")
SmithyHardOre = Region.New("SmithyHardOre")
SmithyBell = Region.New("SmithyBell")
SmithSecret = Region.New("SmithSecret")
SubrosiaChef = Region.New("SubrosiaChef")
SubrosiaMountainWest = Region.New("SubrosiaMountainWest")
SubrosiaMountainLockedChest = Region.New("SubrosiaMountainLockedChest")
SubrosiaMountainWestDigSpot = Region.New("SubrosiaMountainWestDigSpot")
SubrosiaMountainSouthDigSpot = Region.New("SubrosiaMountainSouthDigSpot")
Volcano = Region.New("Volcano")
Fireworks = Region.New("Fireworks")

-- Temple
TempleOfSeasons = Region.New("TempleOfSeasons")
TempleDigSpot = Region.New("TempleDigSpot")
TempleSecret = Region.New("TempleSecret")
TempleWinterFairy = Region.New("TempleWinterFairy")
TempleSummerFairy = Region.New("TempleSummerFairy")
TempleAutumnEntrance = Region.New("TempleAutumnEntrance")
TempleAutumnFairy = Region.New("TempleAutumnFairy")

-- Market
SubrosiaMarket = Region.New("SubrosiaMarket")
RosaDate = Region.New("RosaDate")
SubrosiaMarket1 = Region.New("SubrosiaMarket1")
MarketOrePurchases = Region.New("MarketOrePurchases")
SubrosiaMarket2 = Region.New("SubrosiaMarket2")
SubrosiaMarket3 = Region.New("SubrosiaMarket3")
SubrosiaMarket4 = Region.New("SubrosiaMarket4")
SubrosiaMarket5 = Region.New("SubrosiaMarket5")
BeachDigSpot = Region.New("BeachDigSpot")
SubrosiaMarketUpperDigSpot = Region.New("SubrosiaMarketUpperDigSpot")
SubrosiaMarketLowerDigSpot = Region.New("SubrosiaMarketLowerDigSpot")

-- Village
StrangeBrothers = Region.New("StrangeBrothers")
VillagerGasha = Region.New("VillagerGasha")
StrangeBrothersTreasure = Region.New("StrangeBrothersTreasure")
TempleSpringFairy = Region.New("TempleSpringFairy")
SubrosiaWilds = Region.New("SubrosiaWilds")
SubrosiaWildsMagnet = Region.New("SubrosiaWildsMagnet")
WildsDigSpot = Region.New("WildsDigSpot")
SubrosiaVillagePortal = Region.New("SubrosiaVillagePortal")

-- Pirates
Pirates = Region.New("Pirates")
PirateSecret = Region.New("PirateSecret")

-- Furnace
EastFurnace = Region.New("EastFurnace")
WestFurnace = Region.New("WestFurnace")
SouthFurnace = Region.New("SouthFurnace")
GreatFurnace = Region.New("GreatFurnace")
SignGuy = Region.New("SignGuy")
BombFlowerPickup = Region.New("BombFlowerPickup")
FurnaceTerrace = Region.New("FurnaceTerrace")

-- D8
SwordAndShieldMaze = Region.New("SwordAndShieldMaze")

-- DUNGEONS
-- Hero's Cave
HerosCaveFoyer = Region.New("HerosCaveFoyer")
HerosCaveLedge = Region.New("HerosCaveLedge")
HerosCaveUnderground = Region.New("HerosCaveUnderground")
HerosCavePostKey = Region.New("HerosCavePostKey")

-- Linked Hero's Cave
LinkedCave = Region.New("LinkedCave")
LinkedCaveFoyer = Region.New("LinkedCaveFoyer")
LinkedCaveLedge = Region.New("LinkedCaveLedge")
LinkedCaveF1Chest = Region.New("LinkedCaveF1Chest")
LinkedCaveF2Keydrop = Region.New("LinkedCaveF2Keydrop")
LinkedCaveF2Chest = Region.New("LinkedCaveF2Chest")
LinkedCaveF3TorchKeyDrop = Region.New("LinkedCaveF3TorchKeyDrop")
LinkedCaveF3FloodedRoom = Region.New("LinkedCaveF3FloodedRoom")
LinkedCaveF3FloodedKeydrop = Region.New("LinkedCaveF3FloodedKeydrop")
LinkedCaveF3Chest = Region.New("LinkedCaveF3Chest")
LinkedCaveF4Chest = Region.New("LinkedCaveF4Chest")
LinkedCaveF5Gauntlet = Region.New("LinkedCaveF5Gauntlet")
LinkedCaveF5BoomerangMaze = Region.New("LinkedCaveF5BoomerangMaze")
LinkedCaveFinalChest = Region.New("LinkedCaveFinalChest")

-- Gnarled Root Dungeon
GnarledFoyer = Region.New("GnarledFoyer")
GnarledFloormasters = Region.New("GnarledFloormasters")
GnarledLeftStalfos = Region.New("GnarledLeftStalfos")
GnarledZolRoom = Region.New("GnarledZolRoom")
GnarledGoriyaRoom = Region.New("GnarledGoriyaRoom")
GnarledPushBlocks = Region.New("GnarledPushBlocks")
GnarledMinecartChest = Region.New("GnarledMinecartChest")
GoriyaBros = Region.New("GoriyaBros")
Aquamentus = Region.New("Aquamentus")
GnarledEssence = Region.New("GnarledEssence")
-- items
GnarledRightStalfosChest = Region.New("GnarledRightStalfosChest")
GnarledFloormasterChest = Region.New("GnarledFloormasterChest")
GnarledLeftStalfosChest = Region.New("GnarledLeftStalfosChest")
GnarledGoriyaChest = Region.New("GnarledGoriyaChest")
GnarledLeverChest = Region.New("GnarledLeverChest")
GnarledSpinningBladeChest = Region.New("GnarledSpinningBladeChest")
GnarledPostGoriyaBros = Region.New("GnarledPostGoriyaBros")

-- Snake's Remains
-- locations
SnakeFoyer = Region.New("SnakeFoyer")
SnakeAngryTorches = Region.New("SnakeAngryTorches")
SnakeMoblinRopeFight = Region.New("SnakeMoblinRopeFight")
SnakeRupeeRoom = Region.New("SnakeRupeeRoom")
SnakeHardhats = Region.New("SnakeHardhats")
SnakeBombMoblins = Region.New("SnakeBombMoblins")
SnakeBladeTraps = Region.New("SnakeBladeTraps")
SnakeAltEntrance = Region.New("SnakeAltEntrance")
SnakeBombBlockStairs = Region.New("SnakeBombBlockStairs")
FacadeDoorstep = Region.New("FacadeDoorstep")
Facade = Region.New("Facade")
KingDodongo = Region.New("KingDodongo")
SnakeEssence = Region.New("SnakeEssence")
-- items
SnakeLeftRopeDrop = Region.New("SnakeLeftRopeDrop")
SnakeRightRopeChest = Region.New("SnakeRightRopeChest")
SnakeHardhatChest = Region.New("SnakeHardhatChest")
SnakeBombMoblinChest = Region.New("SnakeBombMoblinChest")
SnakeWildBombsHardhat = Region.New("SnakeWildBombsHardhat")
SnakeWildBombsPolsVoice = Region.New("SnakeWildBombsPolsVoice")
SnakeBombPuzzle = Region.New("SnakeBombPuzzle")
SnakeScrub = Region.New("SnakeScrub")
SnakeTerrace = Region.New("SnakeTerrace")

-- Poison Moth's Lair
PoisonFoyer = Region.New("PoisonFoyer")
PoisonCentral = Region.New("PoisonCentral")
PoisonWaterRoom = Region.New("PoisonWaterRoom")
PoisonPols = Region.New("PoisonPols")
PoisonTrampolineOwl = Region.New("PoisonTrampolineOwl")
PoisonTrampolinePuzzle = Region.New("PoisonTrampolinePuzzle")
PoisonOmuaiDoorstep = Region.New("PoisonOmuaiDoorstep")
Omuai = Region.New("Omuai")
Mothula = Region.New("Mothula")
-- items
PoisonWaterChest = Region.New("PoisonWaterChest")
PoisonTrampolineOwlChest = Region.New("PoisonTrampolineOwlChest")
PoisonZolChest = Region.New("PoisonZolChest")
PoisonRollerChest = Region.New("PoisonRollerChest")
PoisonMoldormChest = Region.New("PoisonMoldormChest")
PoisonBombWallChest = Region.New("PoisonBombWallChest")
PoisonMimicChest = Region.New("PoisonMimicChest")
PoisonTerraceChest = Region.New("PoisonTerraceChest")
PoisonBladeTrapChest = Region.New("PoisonBladeTrapChest")
PoisonEssence = Region.New("PoisonEssence")

-- Dancing Dragon Dungeon
DancingFoyer = Region.New("DancingFoyer")
DancingMinecart = Region.New("DancingMinecart")
DancingAntiFairyMaze = Region.New("DancingAntiFairyMaze")
DancingSpikeTrap = Region.New("DancingSpikeTrap")
DancingPostWaterRollers = Region.New("DancingPostWaterRollers")
DancingMinecartTorches = Region.New("DancingMinecartTorches")
Agunima = Region.New("Agunima")
DancingBranchingMinecart = Region.New("DancingBranchingMinecart")
DancingWizzrobes = Region.New("DancingWizzrobes")
DancingBeamos = Region.New("DancingBeamos")
DancingTorchPit = Region.New("DancingTorchPit")
DancingPotHeaven = Region.New("DancingPotHeaven")
Gohma = Region.New("Gohma")
-- items
DancingPotPush = Region.New("DancingPotPush")
DancingDarkRoomChest = Region.New("DancingDarkRoomChest")
DancingWaterRing = Region.New("DancingWaterRing")
DancingPoolDrop = Region.New("DancingPoolDrop")
DancingScrub = Region.New("DancingScrub")
DancingTorchChest = Region.New("DancingTorchChest")
DancingWildEmbers = Region.New("DancingWildEmbers")
DancingPitRace = Region.New("DancingPitRace")
DancingEyeDive = Region.New("DancingEyeDive")
DancingEssence = Region.New("DancingEssence")

-- Unicorn's Cave
UnicornFoyer = Region.New("UnicornFoyer")
UnicornMinecarts = Region.New("UnicornMinecarts")
UnicornMinecartPushBlock = Region.New("UnicornMinecartPushBlock")
UnicornUndergroundPipesRight = Region.New("UnicornUndergroundPipesRight")
UnicornPotRoom = Region.New("UnicornPotRoom")
UnicornMagnetGloveChest = Region.New("UnicornMagnetGloveChest")
UnicornFireStatues = Region.New("UnicornFireStatues")
UnicornPreSyger = Region.New("UnicornPreSyger")
Syger = Region.New("Syger")
UnicornPostSyger = Region.New("UnicornPostSyger")
UnicornMagnetButton = Region.New("UnicornMagnetButton")
Digdogger = Region.New("Digdogger")
UnicornEssence = Region.New("UnicornEssence")
-- items
UnicornChestLeftOfEntrance = Region.New("UnicornChestLeftOfEntrance")
UnicornTerrace = Region.New("UnicornTerrace")
UnicornSpiralChest = Region.New("UnicornSpiralChest")
UnicornMiddleMinecartChest = Region.New("UnicornMiddleMinecartChest")
UnicornRightMinecartChest = Region.New("UnicornRightMinecartChest")
UnicornArmosPuzzle = Region.New("UnicornArmosPuzzle")
UnicornArmosPuzzleEmbers = Region.New("UnicornArmosPuzzleEmbers")
UnicornSpinnerChest = Region.New("UnicornSpinnerChest")
UnicornGibdoZolChest = Region.New("UnicornGibdoZolChest")
UnicornTreadmillBasement = Region.New("UnicornTreadmillBasement")

-- Ancient Ruins
AncientFoyer = Region.New("AncientFoyer")
AncientRightOfSpinner = Region.New("AncientRightOfSpinner")
AncientRupeeRoom = Region.New("AncientRupeeRoom")
AncientRopeSpinnerWest = Region.New("AncientRopeSpinnerWest")
AncientBeamosPlatforms = Region.New("AncientBeamosPlatforms")
Ancient2FGibdo = Region.New("Ancient2FGibdo")
AncientSpinyTrampoline = Region.New("AncientSpinyTrampoline")
AncientArrowTrap = Region.New("AncientArrowTrap")
AncientArmosDarknutDrop = Region.New("AncientArmosDarknutDrop")
AncientIndyJones = Region.New("AncientIndyJones")
AncientVireDoorstep = Region.New("AncientVireDoorstep")
Vire = Region.New("Vire")
AncientGauntlet = Region.New("AncientGauntlet")
AncientBossDoor = Region.New("AncientBossDoor")
Manhandla = Region.New("Manhandla")
-- items
AncientMagnetBallDrop = Region.New("AncientMagnetBallDrop")
AncientTrappedChest = Region.New("AncientTrappedChest")
AncientNorthOfSpinnerChest = Region.New("AncientNorthOfSpinnerChest")
AncientMagicBoomerangChest = Region.New("AncientMagicBoomerangChest")
AncientBossKeyChest = Region.New("AncientBossKeyChest")
AncientEssence = Region.New("AncientEssence")

-- Explorer's Crypt
-- locations
CryptFoyer = Region.New("CryptFoyer")
Crypt1FLeftOfPoe = Region.New("Crypt1FLeftOfPoe")
Crypt1FLeftOfPoeChest = Region.New("Crypt1FLeftOfPoeChest")
CryptFirstPoe = Region.New("CryptFirstPoe")
Crypt1FKeyRoom = Region.New("Crypt1FKeyRoom")
CryptSurroundedByArmos = Region.New("CryptSurroundedByArmos")
CryptPoeTrampoline = Region.New("CryptQuicksandRoom")
CryptArmosPuzzle = Region.New("CryptArmosPuzzle")
CryptMagunesu = Region.New("CryptMagunesu")
CryptPoe2Trampoline = Region.New("CryptPoe2Trampoline")
CryptPoe2 = Region.New("CryptPoe2")
CryptDarknutBridge = Region.New("CryptDarknutBridge")
CryptDarknutBridgeTrampolines = Region.New("CryptDarknutBridgeTrampolines")
CryptPastDarknutBridge = Region.New("CryptPastDarknutBridge")
CryptFastPlatform = Region.New("CryptFastPlatform")
PoeSisters = Region.New("PoeSisters")
CryptStairMaze = Region.New("CryptStairMaze")
CryptWizzrobeStalfosRoom = Region.New("CryptWizzrobeStalfosRoom")
CryptJumpingStalfos = Region.New("CryptJumpingStalfos")
Gleeok = Region.New("Gleeok")
-- items
CryptWildEmbers = Region.New("CryptWildEmbers")
Crypt1FWizzrobeChest = Region.New("Crypt1FWizzrobeChest")
CryptZolTrampoline = Region.New("CryptZolTrampoline")
Crypt1FKeyRoomChest = Region.New("Crypt1FKeyRoomChest")
CryptArmosPuzzleReward = Region.New("CryptArmosPuzzleReward")
CryptMagunesuReward = Region.New("CryptMagunesuReward")
CryptQuicksandChest = Region.New("CryptQuicksandChest")
CryptFastPlatformChest = Region.New("CryptFastPlatformChest")
CryptStairMazeChest = Region.New("CryptStairMazeChest")
CryptWizzrobeStalfosChest = Region.New("CryptWizzrobeStalfosChest")
CryptJumpingStalfosChest = Region.New("CryptJumpingStalfosChest")
CryptEssence = Region.New("CryptEssence")

-- Sword & Shield Maze
MazeFoyer = Region.New("MazeFoyer")
MazeHardhats = Region.New("MazeHardhats")
MazeBigBladeTrap = Region.New("MazeBigBladeTrap")
MazeSpinner = Region.New("MazeSpinner")
MazeThreeEyeOwl = Region.New("MazeThreeEyeOwl")
MazeFrypolarRoom = Region.New("MazeFrypolarRoom")
Frypolar = Region.New("Frypolar")
MazeIcePuzzle = Region.New("MazeIcePuzzle")
MazeTerrace = Region.New("MazeTerrace")
MazeNevermeltIce = Region.New("MazeNevermeltIce")
MazeNEIceDrop = Region.New("MazeNEIceDrop")
MazeNWIceDrop = Region.New("MazeNWIceDrop")
MazeMedusaDoorstep = Region.New("MazeMedusaDoorstep")
MedusaHead = Region.New("MedusaHead")
MazeEssence = Region.New("MazeEssence")
-- items
MazeEyeDrop = Region.New("MazeEyeDrop")
MazeThreeEyeChest = Region.New("MazeThreeEyeChest")
MazeHardhatDrop = Region.New("MazeHardhatDrop")
MazeArmosChest = Region.New("MazeArmosChest")
MazeSpinnerChest = Region.New("MazeSpinnerChest")
MazeThreeEyeBombChest = Region.New("MazeThreeEyeBombChest")
MazeWildMysteries = Region.New("MazeWildMysteries")
MazeGhostArmos = Region.New("MazeGhostArmos")
MazeSELavaChest = Region.New("MazeSELavaChest")
MazeSparkPots = Region.New("MazeSparkPots")

-- Goal
OnoxCastle = Region.New("OnoxCastle")
Ganon = Region.New("Ganon")